# Generated by Django 5.1.1 on 2024-09-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('education', models.CharField(max_length=256)),
                ('achievements', models.TextField()),
                ('skills', models.CharField(max_length=256)),
                ('workExp', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('projects', models.TextField()),
            ],
        ),
    ]
