# Generated by Django 5.1.1 on 2024-09-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_profile_achievements_remove_profile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(default=''),
        ),
    ]
