# Generated by Django 5.1.1 on 2024-09-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_profile_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='workExp',
            new_name='workexperience',
        ),
    ]
